-- 2026-08-04: a customer-facing order reference.
--
-- `kit_orders.id` is a UUID. It is the right primary key and it stays. It is the
-- wrong thing to read down a phone or quote in a support email, and it was the
-- only reference the t01 order-confirmation email put in front of the customer
-- ("Order ref: 1b429c90-8a80-4c7e-85fb-5873660489fd").
--
-- `order_seq` is our own short, sortable, lab-independent number, rendered as
-- `AP-{order_seq}` in the application layer (lib/orders/orderRef.ts) so the prefix
-- can change without a data migration. Vitall's `vitall_order_id` is deliberately
-- NOT used for this: it is not written yet when the confirmation email fires, and
-- the lab is expected to change to TDL in ~18 months.
--
-- Full options-considered write-up: docs/2026-08-04-customer-facing-order-reference-spec.md
--
-- Depends on 20260804_kit_orders_is_test.sql (the backfill below reads `is_test`).
-- Followed by 20260804_kit_orders_order_seq_start_floor.sql, which pins the
-- sequence's `start_value` as well as its current value; see that file's header
-- for why, and for the note on this date's duplicated ledger entries.
--
-- LEDGER: this one file corresponds to several rows in the applied-migration ledger,
-- because two sessions applied the 2026-08-04 work concurrently and the fix below was
-- landed as its own apply before being folded back in here. Rows belonging to this
-- file: `kit_orders_order_seq`, `kit_orders_order_seq_start`, and
-- `20260804_kit_orders_order_seq`. A first `kit_orders_order_seq` attempt failed on the
-- collision described below and rolled back, leaving no row; that is why this file
-- could be corrected in place rather than superseded. Everything here is safe to
-- re-run EXCEPT the two statements at the foot: once a real customer order exists,
-- `restart`/`set start` would hand out a reference that is already in somebody's inbox.

alter table public.kit_orders
  add column if not exists order_seq bigint generated by default as identity;

comment on column public.kit_orders.order_seq is
  'Customer-facing order reference, rendered as AP-{order_seq}. Live orders start at 10000; values below that belong to internal test orders. Never reuse or renumber: customers quote these.';

create unique index if not exists kit_orders_order_seq_key
  on public.kit_orders (order_seq);

-- Backfill. Adding an identity column assigns values to existing rows in an
-- arbitrary order, so set them explicitly by purchase order. Scoped to `is_test`
-- rows: this renumbers ONLY internal test orders, and is a no-op on any database
-- where a real customer order already exists.
--
-- Two passes, and the first one is not optional. The `add column` above has
-- ALREADY handed these rows 1..N in arbitrary order, so assigning the same range
-- again collides against `kit_orders_order_seq_key` mid-statement: Postgres checks
-- a unique index row by row, not at end of statement, and a plain one-pass update
-- fails with `duplicate key value ... Key (order_seq)=(1) already exists` (observed
-- 2026-08-04). Parking the values in the negative range first frees 1..N.
update public.kit_orders
   set order_seq = -order_seq
 where is_test;

with renumbered as (
  select id, row_number() over (order by created_at, id) as rn
    from public.kit_orders
   where is_test
)
update public.kit_orders ko
   set order_seq = renumbered.rn
  from renumbered
 where ko.id = renumbered.id;

-- Live orders start at AP-10000, above the backfilled test rows (AP-1, AP-2,
-- AP-3), so no real customer is ever handed a reference that reads like one of
-- the internal tests. A non-zero base also stops customer number three learning
-- that they are customer number three.
alter table public.kit_orders
  alter column order_seq restart with 10000;

-- `restart with` moves the CURRENT value but leaves the sequence's `start_value`
-- at 1, so a later bare `restart` (no value) would drop straight back into the
-- test range and collide on `kit_orders_order_seq_key`. Move the floor too.
alter table public.kit_orders
  alter column order_seq set start with 10000;
