import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How Andro Prime collects, stores, and protects your personal data.',
}

export default function PrivacyPage() {
  return (
    <div className="py-20">
      <div className="max-w-4xl mx-auto px-6">

        {/* Header */}
        <div className="border-b-4 border-black pb-12 mb-16">
          <div className="data-label flex items-center gap-3 mb-8">
            <span className="w-12 h-[2px] bg-black" />
            Legal
          </div>
          <h1 className="text-5xl md:text-6xl font-sans font-black text-black uppercase tracking-tighter leading-[0.9] mb-6">
            Privacy Policy
          </h1>
          <p className="font-serif text-lg text-black leading-relaxed">
            Last updated: April 2026. Andro Prime Ltd is committed to protecting your personal data. This policy explains how we collect, use, and protect the information you share with us.
          </p>
        </div>

        {/* Content */}
        <div className="space-y-16 font-serif text-lg text-black leading-relaxed">

          {[
            {
              title: '1. Who we are',
              body: 'Andro Prime Ltd is a wellness information service registered in England and Wales. We operate the website androprime.co.uk and the associated results dashboard. We are the data controller for personal data processed through our platform.',
            },
            {
              title: '2. What data we collect',
              body: 'We collect personal data you provide when ordering a test kit (name, address, email, date of birth), health information generated by the blood test process (biomarker results from our lab partner), payment information processed via Stripe (we do not store card details), and technical data including IP address, browser type, and usage analytics.',
            },
            {
              title: '3. How we use your data',
              body: 'We use your data to fulfil your order and deliver your test kit, process your blood sample with our accredited lab partner, generate your personalised results report and dashboard, send you account and order communications, and comply with our legal obligations.',
            },
            {
              title: '4. Lawful basis for processing',
              body: 'We process your data on the basis of contract performance (to deliver the service you purchased), legitimate interests (to improve our service and prevent fraud), and consent (for marketing communications, which you can withdraw at any time).',
            },
            {
              title: '5. Health data',
              body: 'Your blood test results are special category data under UK GDPR. We process this data only to deliver your results report and recommendations. We never sell or share your health data with third parties for marketing purposes. Your results are stored with bank-level encryption and accessible only through your private dashboard.',
            },
            {
              title: '6. Lab partner data sharing',
              body: 'We share the minimum necessary data with Thriva Solutions (our UKAS ISO 15189 accredited lab partner) to process your blood sample. Thriva processes data under a data processing agreement with Andro Prime and does not use your data for their own purposes.',
            },
            {
              title: '7. Data retention',
              body: 'We retain your account and test data for the duration of your relationship with us and for seven years thereafter to comply with financial and medical record-keeping obligations. You may request deletion of your data at any time, subject to these retention requirements.',
            },
            {
              title: '8. Your rights',
              body: 'Under UK GDPR you have the right to access your personal data, correct inaccurate data, request deletion, object to processing, request restriction, and data portability. To exercise any of these rights, contact us at privacy@androprime.co.uk.',
            },
            {
              title: '9. Cookies',
              body: 'We use essential cookies to operate the site and analytics cookies to understand how visitors use our service. You may decline analytics cookies at any time through our cookie settings.',
            },
            {
              title: '10. Contact',
              body: 'For any privacy queries, contact: privacy@androprime.co.uk. To raise a concern with the regulator: Information Commissioner\'s Office (ICO), ico.org.uk.',
            },
          ].map(({ title, body }) => (
            <div key={title}>
              <h2 className="font-sans font-black uppercase text-2xl tracking-tighter text-black mb-4 border-b-2 border-black pb-4">{title}</h2>
              <p>{body}</p>
            </div>
          ))}
        </div>

      </div>
    </div>
  )
}
