/**
 * register-carousel-run — put the 30-day Instagram carousel run into the database.
 *
 * Plan step 1.1 of `06_marketing/content-machine/2026-08-14-content-machine-plan.md`, the half
 * that follows the `variant` migration (D1, Keith 2026-08-14).
 *
 * WHY IT EXISTS. Thirty carousel posts were created in Metricool on 2026-08-13 and begin
 * publishing on 2026-08-17. Until they are registered they are invisible to `/content-status`,
 * unchecked by `content-doctor`, absent from every count in the STATE docs, and unreachable by
 * `metricool-writeback`, which only asks about renditions it can see. Registered before the run
 * starts, it records itself as it publishes. Registered afterwards, the per-day publish
 * timestamps have to be reconstructed.
 *
 * WHAT IT IS NOT. It does not create anything in Metricool and it never edits a post. The
 * thirty posts already exist; this ADOPTS them, which is a different and much safer act. The
 * only writes are to `content_assets` and `content_renditions`.
 *
 * HOW A POST IS MATCHED TO A ROW, and why it is not by position. The run is generated by
 * `06_marketing/content/instagram/carousel-prototype/schedule.js`, which derives every day from
 * `covers.js` and parses the captions straight out of `captions.md` (the CA-035 artefact). This
 * script asks that same generator for the run, then matches each day to the Metricool post
 * occupying that day's SLOT, and then REFUSES the match unless the post's own text is the
 * approved caption for that topic byte for byte. Sorting two lists and zipping them would look
 * identical on a good day and attach the wrong post id on a bad one, and a wrong id is a
 * rendition that reports someone else's publication as its own.
 *
 * WHAT MAKES A BAD RUN RECOVERABLE: `--dry-run` prints every insert and update it would make and
 * performs none; every write is keyed by slug or by rendition id; nothing is ever deleted; and a
 * second run over an already-registered run reports "no change" rather than duplicating, because
 * the unique key is now `(asset_id, platform, format, variant)`.
 */
import { execFileSync } from 'child_process'
import path from 'path'
import { loadEnvLocal, admin, logRun, repoRoot } from './_shared'
import { utcFromWallClock } from './metricool-writeback'

export const AGENT = 'register-carousel-run'

// ── The run's fixed facts.

/**
 * The carousel run lives on the "Keith Antony AI" brand, NOT the brand `METRICOOL_BLOG_ID`
 * points at.
 *
 * Measured 2026-08-14, not assumed: `METRICOOL_BLOG_ID` is 6633045 ("Keith Andro Prime", the
 * company brand), and listing its scheduler for 2026-08-17 to 2026-09-16 returns ZERO posts.
 * The thirty carousels are on 6693691. Both ids are already public facts in
 * `06_marketing/content/social-channel-setup.md`, so this is a routing constant rather than a
 * credential; the token and user id still come from the environment.
 *
 * Also measured: `GET /scheduler/posts/{id}` answers 200 under EITHER blogId, so
 * `metricool-writeback` can still resolve these posts with the brand it already has. The
 * per-brand id is needed for the LIST endpoint, which is brand-scoped, and that is the only
 * place it is used here.
 */
export const CAROUSEL_BLOG_ID = process.env.METRICOOL_CAROUSEL_BLOG_ID?.trim() || '6693691'

/** Every post on this run occupies 13:00 Europe/London. Asserted by `schedule.js --check`. */
export const SLOT_LOCAL = '13:00:00'
export const RUN_TZ = 'Europe/London'

/** The approval records this run ships under. Written onto every asset row so the trail is joinable. */
export const APPROVAL = {
  preflightDate: '2026-08-12', // CA-034, the per-post pre-flight across all 30 assembled posts
  approvedBy: 'Keith',
  approvedAt: '2026-08-12', // CA-034 (7 of 7 ruled) and CA-035 (captions), both the same day
  series: 'carousel-30-2026-08',
}

// ── Types

export interface RunPost {
  day: number
  slug: string
  close: string
  format: string
  date: string
  headline: string
  live: boolean
  payload: { text: string; firstCommentText: string; media: string[] }
}

export interface MetricoolListed {
  id: string
  wallClock: string
  draft: boolean
  text: string
  firstCommentText: string
  mediaCount: number
  networks: string[]
}

export interface AssetPlan {
  slug: string
  topic: string
  title: string
  articleId: string
  articleSlug: string
  funnelJob: string
  notes: string
  days: number[]
}

export interface RenditionPlan {
  assetSlug: string
  variant: string
  day: number
  scheduledFor: string
  externalPostId: string
  body: string
  firstComment: string
}

export type Refusal = { day: number; slug: string; why: string }

export interface Plan {
  assets: AssetPlan[]
  renditions: RenditionPlan[]
  refusals: Refusal[]
}

// ── The run, from its own generator.

/**
 * Ask `schedule.js` for the run rather than restating it.
 *
 * That file is the only place the rotation, the captions and the media layout agree, and it
 * refuses to emit a schedule that fails its own checks. Re-deriving any of it here would create
 * the second copy the whole design exists to prevent.
 */
export function loadRun(root: string): RunPost[] {
  const dir = path.join(root, 'andro-prime', '06_marketing', 'content', 'instagram', 'carousel-prototype')
  const out = execFileSync('node', ['schedule.js', '--json'], { cwd: dir, encoding: 'utf-8', maxBuffer: 32 * 1024 * 1024 })
  const posts = JSON.parse(out) as RunPost[]
  if (!Array.isArray(posts) || posts.length !== 30) {
    throw new Error(`schedule.js returned ${Array.isArray(posts) ? posts.length : 'non-array'} posts, expected 30. Refusing to register a run that does not match its own generator.`)
  }
  return posts
}

// ── Metricool: list the window, flatten to what a match needs.

export type Lister = (blogId: string, fromIso: string, toIso: string) => Promise<MetricoolListed[]>

export function metricoolLister(
  c: { userId: string; token: string },
  fetchImpl: typeof fetch = fetch,
): Lister {
  return async (blogId, fromIso, toIso) => {
    const q = `blogId=${encodeURIComponent(blogId)}&userId=${encodeURIComponent(c.userId)}&userToken=${encodeURIComponent(c.token)}`
    const url = `https://app.metricool.com/api/v2/scheduler/posts?${q}&start=${fromIso}&end=${toIso}`
    const res = await fetchImpl(url, { headers: { 'X-Mc-Auth': c.token } })
    const text = await res.text()
    if (res.status < 200 || res.status >= 300) throw new Error(`Metricool answered HTTP ${res.status}: ${text.slice(0, 300)}`)
    const parsed = JSON.parse(text) as { data?: Array<Record<string, unknown>> }
    return (parsed.data ?? []).map((p) => {
      const pub = (p.publicationDate ?? {}) as { dateTime?: string }
      const providers = (p.providers ?? []) as Array<{ network?: string }>
      return {
        id: `${p.id ?? ''}`,
        wallClock: pub.dateTime ?? '',
        draft: p.draft === true,
        text: `${p.text ?? ''}`,
        firstCommentText: `${p.firstCommentText ?? ''}`,
        mediaCount: Array.isArray(p.media) ? p.media.length : 0,
        networks: providers.map((x) => `${x.network ?? ''}`),
      }
    })
  }
}

// ── Matching. Pure, so every refusal is testable without a network.

/**
 * Find the Metricool post that IS this run-day, or say why nothing qualifies.
 *
 * Four conditions, and each one has to hold. The slot narrows the candidates; the caption is
 * what proves identity, because a caption is topic-specific and a slot is not. `media` and the
 * network are checked because a post that lost a slide, or that acquired a second network,
 * still occupies the right slot and would otherwise be adopted silently.
 */
export function matchPost(run: RunPost, posts: MetricoolListed[]): { ok: true; post: MetricoolListed } | { ok: false; why: string } {
  const slot = `${run.date}T${SLOT_LOCAL}`
  const atSlot = posts.filter((p) => p.wallClock === slot)
  if (atSlot.length === 0) {
    return { ok: false, why: `no Metricool post at ${slot} ${RUN_TZ}. Day ${run.day} (${run.slug}, close ${run.close}) is unregistered and will publish, if it publishes at all, with nothing recording it.` }
  }
  if (atSlot.length > 1) {
    return { ok: false, why: `${atSlot.length} Metricool posts share the slot ${slot} (ids ${atSlot.map((p) => p.id).join(', ')}). Which one is day ${run.day} cannot be decided from the calendar, and guessing attaches a rendition to someone else's post.` }
  }
  const post = atSlot[0]
  if (post.text.trim() !== run.payload.text.trim()) {
    return { ok: false, why: `the post at ${slot} (id ${post.id}) does not carry the approved caption for "${run.slug}". Its text differs from captions.md, so either the post was edited in Metricool or the slot holds a different topic. Nothing is adopted on a caption mismatch.` }
  }
  if (post.firstCommentText.trim() !== run.payload.firstCommentText.trim()) {
    return { ok: false, why: `the post at ${slot} (id ${post.id}) carries the right caption but a different first comment from the CA-035 artefact.` }
  }
  if (post.mediaCount !== run.payload.media.length) {
    return { ok: false, why: `the post at ${slot} (id ${post.id}) carries ${post.mediaCount} media, and the run says ${run.payload.media.length}. A carousel that quietly lost a slide still posts.` }
  }
  if (!post.networks.includes('instagram')) {
    return { ok: false, why: `the post at ${slot} (id ${post.id}) has no instagram provider (has: ${post.networks.join(', ') || 'none'}).` }
  }
  return { ok: true, post }
}

// ── The plan.

export function assetSlugFor(topic: string): string {
  return `carousel-${topic}`
}

/**
 * Build the whole plan from the run, the matched posts and the published-article lookup.
 *
 * A topic whose canonical article is missing or unpublished is REFUSED for all three of its
 * days rather than registered against a null article: the publish gate would reject the row
 * anyway, and an asset with no canonical article claims its clearance is net-new when it is
 * inherited.
 */
export function buildPlan(args: {
  run: RunPost[]
  posts: MetricoolListed[]
  articles: Map<string, { id: string; status: string }>
}): Plan {
  const { run, posts, articles } = args
  const assets = new Map<string, AssetPlan>()
  const renditions: RenditionPlan[] = []
  const refusals: Refusal[] = []

  for (const day of run) {
    const article = articles.get(day.slug)
    if (!article) {
      refusals.push({ day: day.day, slug: day.slug, why: `no blog_articles row for "${day.slug}". The carousel inherits its claims from that article; without it there is nothing to inherit from.` })
      continue
    }
    if (article.status !== 'published') {
      refusals.push({ day: day.day, slug: day.slug, why: `canonical article "${day.slug}" is "${article.status}", not published. A derivative may not outrun its source (gate_rendition_publish says the same thing).` })
      continue
    }
    const matched = matchPost(day, posts)
    if (!matched.ok) {
      refusals.push({ day: day.day, slug: day.slug, why: matched.why })
      continue
    }

    const slug = assetSlugFor(day.slug)
    const existing = assets.get(slug)
    if (existing) {
      existing.days.push(day.day)
    } else {
      assets.set(slug, {
        slug,
        topic: day.slug,
        title: day.headline,
        articleId: article.id,
        articleSlug: day.slug,
        funnelJob: `problem-aware Instagram carousel for "${day.slug}", 30-day close test`,
        notes: '',
        days: [day.day],
      })
    }

    const scheduledFor = utcFromWallClock(`${day.date}T${SLOT_LOCAL}`, RUN_TZ)
    if (!scheduledFor) {
      refusals.push({ day: day.day, slug: day.slug, why: `could not resolve ${day.date}T${SLOT_LOCAL} ${RUN_TZ} to a UTC instant` })
      continue
    }
    renditions.push({
      assetSlug: slug,
      variant: day.close,
      day: day.day,
      scheduledFor,
      externalPostId: matched.post.id,
      body: day.payload.text,
      firstComment: day.payload.firstCommentText,
    })
  }

  // The notes line is written last, because it names the days, and the days are only complete
  // once every one of that topic's appearances has been through the loop above.
  for (const a of assets.values()) {
    a.days.sort((x, y) => x - y)
    a.notes = [
      `One of ten topics on the 30-day Instagram carousel run (${APPROVAL.series}), run days ${a.days.join(', ')}.`,
      'Three renditions, variants A, B and C: the same eight-slide deck with a different closing slide, which is the experiment.',
      'The three closes ask for different things (A quiz, B the topic kit, C the canonical article), so this asset deliberately carries NO single cta: the cta is a property of the variant, not of the idea. The mapping is fixed in carousel-prototype/closes.js and was approved as CA-031, with close C reframed as a delayed kit offer by K2 of CA-034.',
      'markers are deliberately empty: six of the ten run topics are multi-marker and no approved topic-to-marker mapping exists, so inventing one here would put an unreviewed fact in the store the board reads.',
      'Copy: captions.md (CA-035). Slides: carousel-prototype/decks/. Approval packet: 03_compliance/content-approval/signoff-packet-carousel-30-posts-2026-08-12.md.',
    ].join(' ')
  }

  return { assets: [...assets.values()], renditions, refusals }
}

// ── Reporting

export interface RunResult {
  assetsCreated: string[]
  assetsUpdated: string[]
  assetsUnchanged: string[]
  renditionsCreated: { slug: string; variant: string; day: number; id: string }[]
  renditionsUpdated: { slug: string; variant: string; day: number; id: string; what: string }[]
  renditionsUnchanged: number
  refusals: Refusal[]
  failed: { ref: string; why: string }[]
}

export function exitCodeFor(r: RunResult): 0 | 2 | 3 {
  if (r.failed.length) return 2
  if (r.refusals.length) return 3
  return 0
}

export function render(r: RunResult, opts: { dryRun: boolean }): string {
  const L: string[] = []
  const verb = opts.dryRun ? 'WOULD ' : ''
  L.push(`register-carousel-run${opts.dryRun ? ' (DRY RUN — nothing was written)' : ''}`)
  L.push('─'.repeat(72))
  for (const s of r.assetsCreated) L.push(`  ${verb}CREATE ASSET      ${s}`)
  for (const s of r.assetsUpdated) L.push(`  ${verb}UPDATE ASSET      ${s}`)
  for (const x of r.renditionsCreated) L.push(`  ${verb}CREATE RENDITION  ${x.slug}  variant ${x.variant}  day ${x.day}  metricool ${x.id}`)
  for (const x of r.renditionsUpdated) L.push(`  ${verb}UPDATE RENDITION  ${x.slug}  variant ${x.variant}  day ${x.day}  metricool ${x.id}  (${x.what})`)
  for (const f of r.failed) L.push(`  FAILED   ${f.ref}\n           ${f.why}`)
  for (const f of r.refusals) L.push(`  REFUSED  day ${f.day} ${f.slug}\n           ${f.why}`)
  L.push('')
  L.push(`  assets: ${r.assetsCreated.length} created, ${r.assetsUpdated.length} updated, ${r.assetsUnchanged.length} unchanged.`)
  L.push(`  renditions: ${r.renditionsCreated.length} created, ${r.renditionsUpdated.length} updated, ${r.renditionsUnchanged} unchanged.`)
  if (r.refusals.length) L.push('  A REFUSAL IS A DAY THAT WILL PUBLISH UNRECORDED. Each one names what did not line up.')
  if (!r.assetsCreated.length && !r.renditionsCreated.length && !r.renditionsUpdated.length && !r.failed.length && !r.refusals.length) {
    L.push('  The run is already registered and agrees with its generator. That is a clean run, not a silent one.')
  }
  return L.join('\n')
}

// ── Database

export interface KnownAsset {
  id: string
  status: string
  /** Only the columns this job writes. Anything else is somebody else's to change. */
  row: Record<string, unknown>
}

export interface Store {
  articles(): Promise<Map<string, { id: string; status: string }>>
  assets(): Promise<Map<string, KnownAsset>>
  renditions(assetIds: string[]): Promise<Map<string, { id: string; external_post_id: string | null; scheduled_for: string | null; status: string | null; body: string | null }>>
  upsertAsset(a: AssetPlan): Promise<{ id: string; created: boolean; changed: boolean }>
  createRendition(assetId: string, r: RenditionPlan): Promise<void>
  updateRendition(id: string, patch: Record<string, unknown>): Promise<void>
}

const TOPIC_SLUGS_QUERY = 'id,slug,status'

/** The asset row this job asserts, as one object, so "what it writes" has exactly one definition. */
export function assetRowFor(a: AssetPlan): Record<string, unknown> {
  return {
    slug: a.slug,
    title: a.title,
    status: 'approved',
    content_type: 'educational',
    funnel_stage: 'TOFU',
    funnel_job: a.funnelJob,
    awareness: 'problem-aware',
    cta: null,
    series: APPROVAL.series,
    preflight: 'green',
    preflight_date: APPROVAL.preflightDate,
    canonical_article_id: a.articleId,
    approved_by: APPROVAL.approvedBy,
    approved_at: APPROVAL.approvedAt,
    notes: a.notes,
  }
}

/**
 * Does the live row already say what this job would say?
 *
 * Compared field by field rather than by writing and hoping, because an UPDATE that changes
 * nothing still reports as an update, and a job that claims ten writes on every run teaches its
 * reader to ignore the number. Only the keys this job owns are compared; anything a human has
 * since set on the row is not this job's business.
 */
export function assetMatches(want: Record<string, unknown>, live: Record<string, unknown>): boolean {
  return Object.keys(want).every((k) => {
    const w = want[k] ?? null
    const l = live[k] ?? null
    return `${w}` === `${l}`
  })
}

export function liveStore(): Store {
  return {
    async articles() {
      const { data, error } = await admin().from('blog_articles').select(TOPIC_SLUGS_QUERY)
      if (error) throw new Error(`blog_articles read failed: ${error.message}`)
      return new Map((data ?? []).map((a) => [(a as { slug: string }).slug, { id: (a as { id: string }).id, status: `${(a as { status: unknown }).status}` }]))
    },
    async assets() {
      const cols = 'id,' + Object.keys(assetRowFor({ slug: '', topic: '', title: '', articleId: '', articleSlug: '', funnelJob: '', notes: '', days: [] })).join(',')
      const { data, error } = await admin().from('content_assets').select(cols)
      if (error) throw new Error(`content_assets read failed: ${error.message}`)
      return new Map((data ?? []).map((a) => {
        const row = a as unknown as Record<string, unknown>
        return [`${row.slug}`, { id: `${row.id}`, status: `${row.status}`, row }]
      }))
    },
    async renditions(assetIds) {
      if (!assetIds.length) return new Map()
      const { data, error } = await admin()
        .from('content_renditions')
        .select('id,asset_id,platform,format,variant,external_post_id,scheduled_for,status,body')
        .in('asset_id', assetIds)
      if (error) throw new Error(`content_renditions read failed: ${error.message}`)
      const out = new Map<string, { id: string; external_post_id: string | null; scheduled_for: string | null; status: string | null; body: string | null }>()
      for (const r of data ?? []) {
        const row = r as unknown as { id: string; asset_id: string; platform: string; format: string; variant: string | null; external_post_id: string | null; scheduled_for: string | null; status: string | null; body: string | null }
        out.set(`${row.asset_id}|${row.platform}|${row.format}|${row.variant ?? ''}`, row)
      }
      return out
    },
    async upsertAsset(a) {
      const row = assetRowFor(a)
      const { data: found } = await admin().from('content_assets').select('id').eq('slug', a.slug).maybeSingle()
      if (found) {
        const { error } = await admin().from('content_assets').update(row as never).eq('slug', a.slug)
        if (error) throw new Error(error.message)
        return { id: (found as { id: string }).id, created: false, changed: true }
      }
      const { data, error } = await admin().from('content_assets').insert(row as never).select('id').single()
      if (error) throw new Error(error.message)
      return { id: (data as { id: string }).id, created: true, changed: true }
    },
    async createRendition(assetId, r) {
      const { error } = await admin().from('content_renditions').insert({
        asset_id: assetId,
        platform: 'instagram',
        format: 'carousel',
        variant: r.variant,
        thumb_spec: 'none',
        status: 'scheduled',
        scheduled_for: r.scheduledFor,
        external_post_id: r.externalPostId,
        publisher: 'metricool',
        body: r.body,
        first_comment: r.firstComment,
      } as never)
      if (error) throw new Error(error.message)
    },
    async updateRendition(id, patch) {
      const { error } = await admin().from('content_renditions').update(patch as never).eq('id', id)
      if (error) throw new Error(error.message)
    },
  }
}

// ── Orchestration

export async function apply(plan: Plan, store: Store, dryRun: boolean): Promise<RunResult> {
  const out: RunResult = {
    assetsCreated: [], assetsUpdated: [], assetsUnchanged: [],
    renditionsCreated: [], renditionsUpdated: [], renditionsUnchanged: 0,
    refusals: plan.refusals, failed: [],
  }

  const existingAssets = await store.assets()
  const assetIds = new Map<string, string>()

  for (const a of plan.assets) {
    const known = existingAssets.get(a.slug)
    if (known) assetIds.set(a.slug, known.id)
    // An asset that already says what this job would say is left entirely alone, in a dry run
    // and a live one alike. A no-op UPDATE still reports as a write, and a job that claims ten
    // writes every time it runs teaches its reader to stop reading the number.
    if (known && assetMatches(assetRowFor(a), known.row)) { out.assetsUnchanged.push(a.slug); continue }
    if (dryRun) {
      if (known) out.assetsUpdated.push(a.slug)
      else out.assetsCreated.push(a.slug)
      continue
    }
    try {
      const res = await store.upsertAsset(a)
      assetIds.set(a.slug, res.id)
      if (res.created) out.assetsCreated.push(a.slug)
      else out.assetsUpdated.push(a.slug)
    } catch (e) {
      out.failed.push({ ref: a.slug, why: `content_assets write failed: ${(e as Error).message}` })
    }
  }

  const known = await store.renditions([...assetIds.values()])

  for (const r of plan.renditions) {
    const assetId = assetIds.get(r.assetSlug)
    if (!assetId) {
      // Its asset was refused or failed above. Reported here rather than silently skipped, so a
      // rendition never disappears between the plan and the report.
      if (!dryRun) out.failed.push({ ref: `${r.assetSlug} ${r.variant}`, why: 'its content_assets row does not exist, so the rendition has nothing to hang from' })
      else out.renditionsCreated.push({ slug: r.assetSlug, variant: r.variant, day: r.day, id: r.externalPostId })
      continue
    }
    const existing = known.get(`${assetId}|instagram|carousel|${r.variant}`)
    if (!existing) {
      if (dryRun) { out.renditionsCreated.push({ slug: r.assetSlug, variant: r.variant, day: r.day, id: r.externalPostId }); continue }
      try {
        await store.createRendition(assetId, r)
        out.renditionsCreated.push({ slug: r.assetSlug, variant: r.variant, day: r.day, id: r.externalPostId })
      } catch (e) {
        out.failed.push({ ref: `${r.assetSlug} ${r.variant}`, why: `content_renditions insert failed: ${(e as Error).message}` })
      }
      continue
    }

    // Already registered. Only the three columns this job owns are compared, and a difference is
    // reported by name: silently overwriting a scheduled_for or an id would hide a post that had
    // been moved or replaced in Metricool.
    const patch: Record<string, unknown> = {}
    const diffs: string[] = []
    if ((existing.external_post_id ?? '') !== r.externalPostId) {
      patch.external_post_id = r.externalPostId
      diffs.push(`external_post_id ${existing.external_post_id ?? 'null'} -> ${r.externalPostId}`)
    }
    if (existing.scheduled_for && new Date(existing.scheduled_for).toISOString() !== r.scheduledFor) {
      patch.scheduled_for = r.scheduledFor
      diffs.push(`scheduled_for ${existing.scheduled_for} -> ${r.scheduledFor}`)
    }
    if ((existing.body ?? '').trim() !== r.body.trim()) {
      patch.body = r.body
      diffs.push('body re-synced from captions.md')
    }
    if (!diffs.length) { out.renditionsUnchanged += 1; continue }
    if (dryRun) { out.renditionsUpdated.push({ slug: r.assetSlug, variant: r.variant, day: r.day, id: r.externalPostId, what: diffs.join('; ') }); continue }
    try {
      await store.updateRendition(existing.id, patch)
      out.renditionsUpdated.push({ slug: r.assetSlug, variant: r.variant, day: r.day, id: r.externalPostId, what: diffs.join('; ') })
    } catch (e) {
      out.failed.push({ ref: `${r.assetSlug} ${r.variant}`, why: `content_renditions update failed: ${(e as Error).message}` })
    }
  }

  return out
}

export async function main(): Promise<number> {
  loadEnvLocal()
  const dryRun = process.argv.includes('--dry-run')
  const doLog = process.argv.includes('--log')
  const startedAt = new Date().toISOString()

  const root = repoRoot()
  if (!root) { console.error('register-carousel-run: no repo root found from cwd. Refusing to run.'); return 1 }

  const env = process.env
  const missing = ['METRICOOL_USER_TOKEN', 'METRICOOL_USER_ID'].filter((k) => !env[k]?.trim())
  if (missing.length) {
    console.error(`register-carousel-run: missing credential(s): ${missing.join(', ')}. Refusing to run.`)
    return 1
  }

  const run = loadRun(root)
  const from = `${run[0].date}T00:00:00`
  const to = `${run[run.length - 1].date}T23:59:59`
  const posts = await metricoolLister({ userId: env.METRICOOL_USER_ID ?? '', token: env.METRICOOL_USER_TOKEN ?? '' })(CAROUSEL_BLOG_ID, from, to)

  const store = liveStore()
  const plan = buildPlan({ run, posts, articles: await store.articles() })
  const result = await apply(plan, store, dryRun)

  console.log(render(result, { dryRun }))
  const code = exitCodeFor(result)
  if (doLog && !dryRun) {
    await logRun({
      agent: AGENT,
      status: code === 0 ? 'ok' : code === 2 ? 'error' : 'blocked',
      detail: { exit_code: code, assets_created: result.assetsCreated, renditions_created: result.renditionsCreated.length, refusals: result.refusals, failed: result.failed },
      startedAt,
    })
  }
  return code
}

/** Exact basename, never a suffix match — `test-register-carousel-run.ts` ends with this name. */
export function isDirectInvocation(argv1: string | undefined): boolean {
  if (!argv1) return false
  const base = path.basename(argv1)
  return base === 'register-carousel-run.ts' || base === 'register-carousel-run.js'
}

/** `process.exitCode`, not `process.exit(code)`: the latter crashes on this machine (libuv). */
if (isDirectInvocation(process.argv[1])) {
  main()
    .then((code) => { process.exitCode = code })
    .catch((e) => {
      console.error('REGISTER-CAROUSEL-RUN ERROR:', (e as Error).message)
      process.exitCode = 1
    })
}
