import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The terms and conditions governing your use of Andro Prime products and services.',
}

export default function TermsPage() {
  return (
    <div className="py-20">
      <div className="max-w-4xl mx-auto px-6">

        {/* Header */}
        <div className="border-b-4 border-black pb-12 mb-16">
          <div className="data-label flex items-center gap-3 mb-8">
            <span className="w-12 h-[2px] bg-black" />
            Legal
          </div>
          <h1 className="text-5xl md:text-6xl font-sans font-black text-black uppercase tracking-tighter leading-[0.9] mb-6">
            Terms of Service
          </h1>
          <p className="font-serif text-lg text-black leading-relaxed">
            Last updated: April 2026. Please read these terms carefully before purchasing from Andro Prime Ltd.
          </p>
        </div>

        {/* Content */}
        <div className="space-y-16 font-serif text-lg text-black leading-relaxed">

          {[
            {
              title: '1. About Andro Prime',
              body: 'Andro Prime Ltd is a wellness information service registered in England and Wales. We provide at-home blood test kits and wellness information. We are not a medical service. We do not provide medical advice, diagnosis, or treatment. Our service is not regulated by the CQC.',
            },
            {
              title: '2. Wellness service, not medical advice',
              body: 'Your results report provides wellness information based on your biomarker data. It does not constitute medical advice. Andro Prime is not responsible for any decisions you make based on your results. If you have health concerns, consult a qualified medical practitioner. Our results describe what your levels are — they do not diagnose conditions or recommend treatments.',
            },
            {
              title: '3. Eligibility',
              body: 'You must be 18 or over and resident in the United Kingdom to purchase from Andro Prime. Our kits are designed for use by adult males. By purchasing, you confirm you meet these criteria.',
            },
            {
              title: '4. Orders and payment',
              body: 'Orders are accepted and payment processed via Stripe. Your order is confirmed when you receive a confirmation email. We reserve the right to cancel orders at our discretion. Prices include VAT where applicable.',
            },
            {
              title: '5. Delivery',
              body: 'We dispatch test kits via Royal Mail. Standard delivery is included in the kit price. We are not responsible for delays caused by Royal Mail or circumstances outside our control. Risk in goods passes to you on delivery.',
            },
            {
              title: '6. Returns and refunds',
              body: 'Unused, sealed test kits may be returned within 14 days for a full refund. Once a kit has been activated or a sample posted, we cannot offer a refund as the laboratory process has been initiated. To initiate a return, contact support@androprime.co.uk.',
            },
            {
              title: '7. Results accuracy',
              body: 'Blood test results are generated by Thriva Solutions, our UKAS ISO 15189 accredited laboratory partner. While lab results are highly accurate, no diagnostic test is infallible. Results may be affected by sample quality, timing, and other factors. If you have concerns about your results, consult a GP.',
            },
            {
              title: '8. Supplement products',
              body: 'Our supplement products are food supplements, not medicines. They should not be used as a substitute for a varied and balanced diet and healthy lifestyle. Health claims are EFSA-approved. If you are taking medication or under medical supervision, consult your doctor before use.',
            },
            {
              title: '9. Founding member deposits',
              body: 'The £75 founding member deposit is fully refundable at any time upon written request to support@androprime.co.uk. The deposit does not constitute a contract for clinical services. No clinical services are currently available. The deposit secures your place in the queue when our regulated clinical service launches, subject to eligibility.',
            },
            {
              title: '10. Intellectual property',
              body: 'All content on this website, including text, design, and code, is the intellectual property of Andro Prime Ltd and may not be reproduced without our written permission.',
            },
            {
              title: '11. Limitation of liability',
              body: 'To the fullest extent permitted by law, Andro Prime Ltd shall not be liable for any indirect, incidental, or consequential loss arising from your use of our service. Our total liability to you shall not exceed the amount you paid for the product or service in question.',
            },
            {
              title: '12. Governing law',
              body: 'These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.',
            },
            {
              title: '13. Contact',
              body: 'For any queries about these terms: support@androprime.co.uk.',
            },
          ].map(({ title, body }) => (
            <div key={title}>
              <h2 className="font-sans font-black uppercase text-2xl tracking-tighter text-black mb-4 border-b-2 border-black pb-4">{title}</h2>
              <p>{body}</p>
            </div>
          ))}
        </div>

      </div>
    </div>
  )
}
