/* GENERATED by `node plan.js --json > run-status.js`. Do not hand-edit:
 * the schedule lives in covers.js and this is only its shadow. */
window.RUN = {
  "generated": "2026-08-11",
  "runDays": 30,
  "balance": {
    "fmt": {
      "video": 15,
      "type": 15
    },
    "close": {
      "A": 10,
      "B": 10,
      "C": 10
    },
    "locked": 0,
    "ok": true,
    "problems": []
  },
  "topics": [
    {
      "slug": "14-signs-of-vitamin-d-deficiency",
      "index": 0,
      "eyebrow": "Vitamin D",
      "l1": "14 SIGNS OF",
      "l2": "LOW VITAMIN D",
      "typeBg": "black",
      "deck": true,
      "frame": true
    },
    {
      "slug": "b12-blood-test",
      "index": 1,
      "eyebrow": "B12",
      "l1": "WHAT YOUR B12",
      "l2": "REALLY SAYS",
      "typeBg": "white",
      "deck": true,
      "frame": false
    },
    {
      "slug": "ferritin-blood-test",
      "index": 2,
      "eyebrow": "Ferritin",
      "l1": "YOUR IRON",
      "l2": "STORES, EXPLAINED",
      "typeBg": "black",
      "deck": true,
      "frame": false
    },
    {
      "slug": "crp-blood-test",
      "index": 3,
      "eyebrow": "hs-CRP",
      "l1": "WHAT CRP",
      "l2": "ACTUALLY MEANS",
      "typeBg": "white",
      "deck": true,
      "frame": false
    },
    {
      "slug": "why-am-i-always-tired",
      "index": 4,
      "eyebrow": "Tiredness",
      "l1": "WHY AM I",
      "l2": "ALWAYS TIRED?",
      "typeBg": "black",
      "deck": true,
      "frame": true
    },
    {
      "slug": "brain-fog",
      "index": 5,
      "eyebrow": "Brain fog",
      "l1": "WHAT CAUSES",
      "l2": "BRAIN FOG?",
      "typeBg": "white",
      "deck": true,
      "frame": false
    },
    {
      "slug": "free-androgen-index",
      "index": 6,
      "eyebrow": "Free androgen",
      "l1": "THE NUMBER",
      "l2": "GPS OFTEN MISS",
      "typeBg": "black",
      "deck": true,
      "frame": false
    },
    {
      "slug": "how-to-increase-testosterone-naturally",
      "index": 7,
      "eyebrow": "Testosterone",
      "l1": "WHAT ACTUALLY RAISES",
      "l2": "TESTOSTERONE",
      "typeBg": "white",
      "deck": true,
      "frame": false
    },
    {
      "slug": "myth-of-normal-range",
      "index": 8,
      "eyebrow": "Reference range",
      "l1": "WHAT \"NORMAL\"",
      "l2": "REALLY MEANS",
      "typeBg": "black",
      "deck": true,
      "frame": false
    },
    {
      "slug": "how-to-read-blood-test-results",
      "index": 9,
      "eyebrow": "Blood tests",
      "l1": "HOW TO READ",
      "l2": "YOUR RESULTS",
      "typeBg": "white",
      "deck": true,
      "frame": false
    }
  ],
  "posts": [
    {
      "day": 1,
      "topic": 0,
      "appearance": 0,
      "format": "video",
      "close": "A"
    },
    {
      "day": 2,
      "topic": 1,
      "appearance": 0,
      "format": "type",
      "close": "B"
    },
    {
      "day": 3,
      "topic": 2,
      "appearance": 0,
      "format": "video",
      "close": "C"
    },
    {
      "day": 4,
      "topic": 3,
      "appearance": 0,
      "format": "type",
      "close": "A"
    },
    {
      "day": 5,
      "topic": 4,
      "appearance": 0,
      "format": "video",
      "close": "B"
    },
    {
      "day": 6,
      "topic": 5,
      "appearance": 0,
      "format": "type",
      "close": "C"
    },
    {
      "day": 7,
      "topic": 6,
      "appearance": 0,
      "format": "video",
      "close": "A"
    },
    {
      "day": 8,
      "topic": 7,
      "appearance": 0,
      "format": "type",
      "close": "B"
    },
    {
      "day": 9,
      "topic": 8,
      "appearance": 0,
      "format": "video",
      "close": "C"
    },
    {
      "day": 10,
      "topic": 9,
      "appearance": 0,
      "format": "type",
      "close": "A"
    },
    {
      "day": 11,
      "topic": 0,
      "appearance": 1,
      "format": "type",
      "close": "B"
    },
    {
      "day": 12,
      "topic": 1,
      "appearance": 1,
      "format": "video",
      "close": "C"
    },
    {
      "day": 13,
      "topic": 2,
      "appearance": 1,
      "format": "type",
      "close": "A"
    },
    {
      "day": 14,
      "topic": 3,
      "appearance": 1,
      "format": "video",
      "close": "B"
    },
    {
      "day": 15,
      "topic": 4,
      "appearance": 1,
      "format": "type",
      "close": "C"
    },
    {
      "day": 16,
      "topic": 5,
      "appearance": 1,
      "format": "video",
      "close": "A"
    },
    {
      "day": 17,
      "topic": 6,
      "appearance": 1,
      "format": "type",
      "close": "B"
    },
    {
      "day": 18,
      "topic": 7,
      "appearance": 1,
      "format": "video",
      "close": "C"
    },
    {
      "day": 19,
      "topic": 8,
      "appearance": 1,
      "format": "type",
      "close": "A"
    },
    {
      "day": 20,
      "topic": 9,
      "appearance": 1,
      "format": "video",
      "close": "B"
    },
    {
      "day": 21,
      "topic": 0,
      "appearance": 2,
      "format": "video",
      "close": "C"
    },
    {
      "day": 22,
      "topic": 1,
      "appearance": 2,
      "format": "type",
      "close": "A"
    },
    {
      "day": 23,
      "topic": 2,
      "appearance": 2,
      "format": "video",
      "close": "B"
    },
    {
      "day": 24,
      "topic": 3,
      "appearance": 2,
      "format": "type",
      "close": "C"
    },
    {
      "day": 25,
      "topic": 4,
      "appearance": 2,
      "format": "video",
      "close": "A"
    },
    {
      "day": 26,
      "topic": 5,
      "appearance": 2,
      "format": "type",
      "close": "B"
    },
    {
      "day": 27,
      "topic": 6,
      "appearance": 2,
      "format": "video",
      "close": "C"
    },
    {
      "day": 28,
      "topic": 7,
      "appearance": 2,
      "format": "type",
      "close": "A"
    },
    {
      "day": 29,
      "topic": 8,
      "appearance": 2,
      "format": "video",
      "close": "B"
    },
    {
      "day": 30,
      "topic": 9,
      "appearance": 2,
      "format": "type",
      "close": "C"
    }
  ]
};
