import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { MDXRemote } from 'next-mdx-remote/rsc'
import type { Pluggable } from 'unified'
import rehypeSlug from 'rehype-slug'
import rehypeAutolinkHeadings from 'rehype-autolink-headings'
import rehypeExternalLinks from 'rehype-external-links'
import { getAllArticles, getArticle, extractH2Headings, shouldShowToc } from '@/lib/blog'
import { getAuthor } from '@/lib/authors'
import ArticleLayout from '@/components/marketing/ArticleLayout'
import PullQuote from '@/components/marketing/PullQuote'
import StatBox from '@/components/marketing/StatBox'
import EvidenceBox from '@/components/marketing/EvidenceBox'
import { JsonLd } from '@/components/shared/JsonLd'

const BASE_URL = 'https://andro-prime.com'

const mdxComponents = { PullQuote, StatBox, EvidenceBox }

const rehypePlugins: Pluggable[] = [
  rehypeSlug,
  [
    rehypeAutolinkHeadings,
    {
      behavior: 'wrap',
      properties: { className: ['heading-anchor'] },
    },
  ],
  [
    rehypeExternalLinks,
    {
      target: '_blank',
      rel: ['noopener', 'noreferrer'],
      protocols: ['http', 'https'],
    },
  ],
]

const mdxOptions = {
  mdxOptions: { rehypePlugins },
}

interface Props {
  params: Promise<{ slug: string }>
}

export async function generateStaticParams() {
  return getAllArticles().map((a) => ({ slug: a.slug }))
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  try {
    const { frontmatter } = getArticle(slug)
    const canonical = `${BASE_URL}/blog/${slug}`
    // Per-article OG image: explicit frontmatter.imgSrc overrides; otherwise use the
    // brand-styled dynamic OG generated by /api/og/blog/[slug]/route.tsx.
    const ogImage = frontmatter.imgSrc ?? `${BASE_URL}/api/og/blog/${slug}`
    return {
      title: `${frontmatter.title} | Andro Prime`,
      description: frontmatter.excerpt,
      alternates: { canonical },
      openGraph: {
        title: `${frontmatter.title} | Andro Prime`,
        description: frontmatter.excerpt,
        url: canonical,
        type: 'article',
        images: [{ url: ogImage, width: 1200, height: 630, alt: frontmatter.title }],
      },
      twitter: {
        card: 'summary_large_image',
        title: `${frontmatter.title} | Andro Prime`,
        description: frontmatter.excerpt,
        images: [ogImage],
      },
    }
  } catch {
    return {}
  }
}

export default async function ArticlePage({ params }: Props) {
  const { slug } = await params
  try {
    const { content, frontmatter, wordCount } = getArticle(slug)
    const headings = extractH2Headings(content)
    const showToc = shouldShowToc(frontmatter, wordCount)

    const author = frontmatter.authorSlug ? getAuthor(frontmatter.authorSlug) : undefined
    const reviewer = frontmatter.reviewerSlug ? getAuthor(frontmatter.reviewerSlug) : undefined

    const datePublished = frontmatter.isoDate ?? frontmatter.date
    const dateModified = frontmatter.dateModified ?? datePublished

    // Author block: prefer @id reference into author page Person schema when authorSlug is set.
    // Fall back to inline Person for legacy articles still on `author` string field.
    const authorBlock = author
      ? { '@id': `${BASE_URL}/authors/${author.slug}/#person` }
      : { '@type': 'Person', name: frontmatter.author ?? 'Andro Prime' }

    const graph: Record<string, unknown>[] = [
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: BASE_URL },
          { '@type': 'ListItem', position: 2, name: 'Blog', item: `${BASE_URL}/blog` },
          { '@type': 'ListItem', position: 3, name: frontmatter.title, item: `${BASE_URL}/blog/${slug}` },
        ],
      },
      {
        '@type': 'Article',
        '@id': `${BASE_URL}/blog/${slug}/#article`,
        headline: frontmatter.title,
        description: frontmatter.excerpt,
        datePublished,
        dateModified,
        inLanguage: 'en-GB',
        author: authorBlock,
        ...(reviewer
          ? { reviewedBy: { '@id': `${BASE_URL}/authors/${reviewer.slug}/#person` } }
          : {}),
        publisher: { '@id': `${BASE_URL}/#organization` },
        mainEntityOfPage: {
          '@type': 'WebPage',
          '@id': `${BASE_URL}/blog/${slug}`,
        },
        ...(frontmatter.imgSrc ? { image: `${BASE_URL}${frontmatter.imgSrc}` } : {}),
      },
    ]

    if (frontmatter.faq && frontmatter.faq.length > 0) {
      graph.push({
        '@type': 'FAQPage',
        '@id': `${BASE_URL}/blog/${slug}/#faq`,
        mainEntity: frontmatter.faq.map((item) => ({
          '@type': 'Question',
          name: item.q,
          acceptedAnswer: { '@type': 'Answer', text: item.a },
        })),
      })
    }

    const articleSchema = {
      '@context': 'https://schema.org',
      '@graph': graph,
    }

    return (
      <>
        <JsonLd data={articleSchema} />
        <ArticleLayout frontmatter={frontmatter} headings={headings} showToc={showToc}>
          <MDXRemote source={content} components={mdxComponents} options={mdxOptions} />
        </ArticleLayout>
      </>
    )
  } catch {
    notFound()
  }
}
