// Reusable brand logo. Renders the Interlocked AP: the mark alone, or the full lockup.
// Path data lives in ./logoArt (auto-generated by
// 02_brand/assets/logos/interlocked-ap/gen-logo.js --install); see that folder's README.
//
// 🔴 THERE IS NO CONTAINER ANY MORE. The Refined Monogram sat inside a 100x100 black square and
// this component drew that square, which is why callers could pass viewBox="0 0 100 100" to crop
// down to a square icon. The Interlocked AP is an open glyph with no container by specification, so
// the rect is gone and that cropping trick no longer works: use `mark` instead, which swaps in the
// mark's own viewBox rather than clipping the lockup's.
//
// The mark and the wordmark need DIFFERENT fill rules. The mark is drawn nonzero; the wordmark is
// traced from the approved artwork and potrace nests its contours by winding, so it needs evenodd.
// Drawing both nonzero fills every counter in the wordmark.
import type { SVGProps } from 'react'
import {
  MARK_PATH,
  MARK_VIEWBOX,
  LOCKUP_MARK_PATH,
  LOCKUP_WORD_PATH,
  LOCKUP_WORD_FILL_RULE,
  LOCKUP_VIEWBOX,
} from './logoArt'

type LogoVariant = 'dark' | 'light'

interface LogoProps extends SVGProps<SVGSVGElement> {
  /**
   * 'dark' = black ink, for light backgrounds (default).
   * 'light' = white ink, for dark backgrounds.
   * The names describe the INK, not the ground, and are kept from the previous component so the
   * existing call sites keep meaning what they meant.
   */
  variant?: LogoVariant
  /** Render the mark on its own, without the ANDRO PRIME wordmark. */
  mark?: boolean
}

export function Logo({ variant = 'dark', mark = false, ...props }: LogoProps) {
  const ink = variant === 'dark' ? '#000000' : '#ffffff'
  return (
    <svg
      viewBox={mark ? MARK_VIEWBOX : LOCKUP_VIEWBOX}
      role="img"
      aria-label="Andro Prime"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {mark ? (
        <path d={MARK_PATH} fill={ink} fillRule="nonzero" />
      ) : (
        <>
          <path d={LOCKUP_MARK_PATH} fill={ink} fillRule="nonzero" />
          <path d={LOCKUP_WORD_PATH} fill={ink} fillRule={LOCKUP_WORD_FILL_RULE} />
        </>
      )}
    </svg>
  )
}
