// Reusable brand logo. Renders the Interlocked AP: the mark alone, or the full lockup.
// Path data lives in ./logoArt (auto-generated by
// 02_brand/assets/logos/interlocked-ap/gen-logo.js --install); see that folder's README.
//
// 🔴 THERE IS NO CONTAINER ANY MORE. The Refined Monogram sat inside a 100x100 black square and
// this component drew that square, which is why callers could pass viewBox="0 0 100 100" to crop
// down to a square icon. The Interlocked AP is an open glyph with no container by specification, so
// the rect is gone and that cropping trick no longer works: use `mark` instead, which swaps in the
// mark's own viewBox rather than clipping the lockup's.
//
// The mark and the wordmark need DIFFERENT fill rules. The mark is drawn nonzero; the wordmark is
// traced from the approved artwork and potrace nests its contours by winding, so it needs evenodd.
// Drawing both nonzero fills every counter in the wordmark.
import type { SVGProps } from 'react'
import {
  MARK_PATH,
  MARK_VIEWBOX,
  LOCKUP_MARK_PATH,
  LOCKUP_WORD_PATH,
  LOCKUP_WORD_FILL_RULE,
  LOCKUP_VIEWBOX,
} from './logoArt'

// 🔴 SIZING. The lockup's aspect is 9.32, where the Refined Monogram's was 4.7, because that one
// spent half its width on a black square and this one does not. So the SAME css height renders the
// wordmark more than twice as large, and the first install of this logo looked overpowering in the
// nav for exactly that reason: h-6 had been fine on a 4.7 lockup and is not on a 9.32 one.
//
// Size by the WORDMARK'S CAP HEIGHT, not by the element height:
//
//     wordmark cap height ≈ 0.663 × the rendered height of the lockup
//
// The nav's own links are 12px, so a cap of roughly 8.4px. The logo should read as the brand and
// sit slightly above them, not shout: h-4 (16px) puts the cap at 10.6px, which is where it landed
// after rendering the whole ladder from 14px to 24px and looking at it. If a new placement needs a
// size, work back from the surrounding type the same way rather than reusing a number from here.
type LogoVariant = 'dark' | 'light'

interface LogoProps extends SVGProps<SVGSVGElement> {
  /**
   * 'dark' = black ink, for light backgrounds (default).
   * 'light' = white ink, for dark backgrounds.
   * The names describe the INK, not the ground, and are kept from the previous component so the
   * existing call sites keep meaning what they meant.
   */
  variant?: LogoVariant
  /** Render the mark on its own, without the ANDRO PRIME wordmark. */
  mark?: boolean
}

export function Logo({ variant = 'dark', mark = false, ...props }: LogoProps) {
  const ink = variant === 'dark' ? '#000000' : '#ffffff'
  return (
    <svg
      viewBox={mark ? MARK_VIEWBOX : LOCKUP_VIEWBOX}
      role="img"
      aria-label="Andro Prime"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      {mark ? (
        <path d={MARK_PATH} fill={ink} fillRule="nonzero" />
      ) : (
        <>
          <path d={LOCKUP_MARK_PATH} fill={ink} fillRule="nonzero" />
          <path d={LOCKUP_WORD_PATH} fill={ink} fillRule={LOCKUP_WORD_FILL_RULE} />
        </>
      )}
    </svg>
  )
}
